### ISSUE TITLE
Flat expansion panels jerk when opening

### ISSUE THREAD

**Issue by timtraversy** [angulardart/angular_components#383]
This issue can be observed in the Angular Components gallery:
https://dart-lang.github.io/angular_components/#/material_expansion_panel

When a flat expansion panel is opened, the opening animation jerks to completion. It looks like it is about to open smoothly, and then it just jumps, as if it its initial size calculation was mistaken.

Also, I can open a second issue for this, but expansion panels have a highlighted gray color after being dismissed. Is this intentional?

**Comment by nshahan** [comment]
cc @phantomesse

**Comment by phantomesse** [comment]
Hi Tim! Thank you for your feedback.

I'm not seeing the animation jerk for the flat expansion panels. Can you take a screencast?

The highlighted gray color indicates a focus state. When you've clicked on a panel to collapse it, it is highlighted in gray because it's still in focus.

**Comment by timtraversy** [comment]
Ok understood about the focus! Here's a video of the jerk I'm seeing: https://drive.google.com/file/d/1bTM4S_nSpoCCOfkZrtLuaHA1_mzMThIR/view?usp=sharing

It happens just as the animation is about to complete.

**Comment by TedSander** [comment]
@timtraversy what is your environment for that animation?

MacOS Chrome looks pretty smooth to me, but I definitely see it isn't smooth in the video.

**Comment by timtraversy** [comment]
Oh I see. I just tested on Mac Chrome and it looks fine there. I'm seeing the issue on Safari 12.1.

**Comment by timtraversy** [comment]
Is this planned to be supported on Safari?

**Comment by TedSander** [comment]
Pretty low priority for us compared to all the other things we are working
on. I don't see us fixing it anytime soon.
